import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Lazy-loaded Gemini client to prevent startup crashes if API key is missing
let aiClient: GoogleGenAI | null = null;

function getGemini(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY environment variable is not configured in the Secrets manager.");
    }
    aiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// Design Consultant API Endpoint
app.post("/api/ai/critique", async (req, res) => {
  try {
    const { concept, lang } = req.body;
    if (!concept) {
      return res.status(400).json({ error: "No concept provided." });
    }

    const ai = getGemini();

    const systemInstruction = lang === "zh" 
      ? "你是一位精通‘技术与纸张物理美学’的跨国高级设计总监。你会分析用户的设计理念，给出专业、客观、富有诗意的建议。必须输出符合Schema格式的JSON数据。"
      : "You are an international creative director specialized in 'physical papercraft textures combined with high-tech layouts'. You critique designer concepts and supply rich aesthetic tips. You must output JSON conforming to the requested schema.";

    const promptMessage = lang === "zh"
      ? `分析以下设计理念，并给出具有纸张化和科技感双重魅力的深度分析。请用简体中文填写返回的字符串字段。\n理念名/描述: "${concept}"`
      : `Analyze the following design concept, providing a deep critique balancing papercraft tactile physical beauty and tech-forward layouts. Return text fields in English.\nConcept name/description: "${concept}"`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: promptMessage,
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.8,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            score: { 
              type: Type.INTEGER, 
              description: "Aesthetics layout rating score (40 to 100)" 
            },
            conceptAnalysis: { 
              type: Type.STRING, 
              description: "A professional design analysis of the coordinate flow, balance, and aesthetic texture potential." 
            },
            recommendations: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "3 concrete, actionable recommendations on typography pairings, alignment, or material physics."
            },
            creativeKeywords: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "3 evocative aesthetic words representing the refined concept."
            },
            tactileTip: { 
              type: Type.STRING, 
              description: "A physical tip on how to translate this project into a folded paper, blind debossed, or organic grain layout." 
            }
          },
          required: ["score", "conceptAnalysis", "recommendations", "creativeKeywords", "tactileTip"],
        },
      },
    });

    const responseText = response.text;
    if (!responseText) {
      throw new Error("No response content generated by Gemini.");
    }

    const payload = JSON.parse(responseText.trim());
    return res.json(payload);
  } catch (error: any) {
    console.error("AI Critique Error:", error);
    return res.status(500).json({ 
      error: error.message || "Failed to process the design critique.",
      details: "Check if the GEMINI_API_KEY is configured in your project secrets."
    });
  }
});

// Setup Server Static / Developer hot-reload configuration
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    // Development mode leveraging Vite as dev middleware
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Production mode serving bundled static single-page resources
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server successfully listening on http://0.0.0.0:${PORT} [ENV: ${process.env.NODE_ENV || "development"}]`);
  });
}

startServer().catch((err) => {
  console.error("Failed to initialize server stack:", err);
});
