import { ProjectItem, LocaleContent, PaperElement } from "./types";

export const portfolioProjects: ProjectItem[] = [
  {
    id: "proj-01",
    titleEn: "Origami Crease Blueprint",
    titleZh: "折纸褶皱几何图谱",
    categoryEn: "Creative Engineering / Graphics",
    categoryZh: "创意交互工程 / 图性学",
    year: "2026",
    roleEn: "Principal Designer & Software Artist",
    roleZh: "首席视觉设计师 & 创意软件艺术家",
    summaryEn: "An interactive, computational study of mathematical folding creases mapped directly onto debossed, textured cotton fiberboards.",
    summaryZh: "一门将数学折叠折痕通过交互计算，直接映射到压凹纯棉高细度纤维板上的混合实体视觉研究。",
    detailsEn: "This project explores the threshold between physical paper folds and software-generated vectors. Users interact with a virtual crease simulator which then calculates physical tension states, outputting high-precision coordinates for heavy-pressure steel-die debossing. The physical works are coupled with an immersive digital shader mimicking mechanical tension stresses.",
    detailsZh: "该项目探索实体纸张折痕与软件生成矢量之间的几何阈值。用户与虚拟折痕模拟器交互，计算出重压钢模凹版印刷所需的纸张拉力形变状态与精密向量坐标。物理纸雕作品搭载了一台模拟机械拉力形变的数字视觉着色器，融合数实两端的感官张力。",
    paperGrammage: "350g Crane Crest Pure Cotton Paper, Blind Debossed",
    colorHex: "#e3dfd5",
    technicalCoordinations: ["GRID_STRESS_X_440", "TENSION_COEFF: 0.84", "ANGLE_ROT: 14.5°"],
    featuresEn: ["Real-time digital crease mapping", "Zero-ink high precision mechanical debossing", "Bilinear mathematical stress evaluation"],
    featuresZh: ["实时数字折痕刚性折叠映射", "无油墨高精度钢板机械凹印", "双线性数学拉力负载评估"]
  },
  {
    id: "proj-02",
    titleEn: "Algorithmic Deck Plotter",
    titleZh: "算力向量卡牌绘图仪",
    categoryEn: "Generative Branding / Packaging",
    categoryZh: "生成式品牌系统 / 纸艺包装",
    year: "2025",
    roleEn: "Creative Technologist",
    roleZh: "创意技术专家 / 媒介程序设计师",
    summaryEn: "A hardware-software generative branding system utilizing real-world mechanical plotters to render code-driven graphics on heavy textured sand papers.",
    summaryZh: "一个借助真实机械绘图机在重质粗砂纹理纸上，绘制完全由代码驱动的符号图形之软硬件生成式品牌系统。",
    detailsEn: "Using real-time physical canvas constraints, the Algorithmic Deck Plotter turns system logs and metadata of client requests into precise pen-drawn shapes on recycled, rough grain pulp paper. The result is an artisanal deck where every card features a unique, numbered generative graphic frame and high fidelity vector coordinates printed on the margins.",
    detailsZh: "利用实时物理画布约束条件，该系统将客户端请求产生的元数据与系统日志转化成精细的笔式机械绘图笔迹，刻画在粗面再生环保砂面纸上。这套特制的创意套牌中，每一张均有唯一的、编号分明的生成式坐标边界与印刻边缘的机器符号元数据。",
    paperGrammage: "280g Recycled Rough Pulped Eco-Kraft Card",
    colorHex: "#eae5d9",
    technicalCoordinations: ["DEVICE_PLOTTER_09", "PEN_PRESSURE: 110mN", "MARGIN_COORD_AUTO"],
    featuresEn: ["Generative pen-plotting scripts", "Rough fibrous organic canvas texturing", "Live hardware output synchrony"],
    featuresZh: ["生成式机械手笔绘脚本", "高粗面纤维有机骨架画布纹理", "物理硬件现场绘制同步控制"]
  },
  {
    id: "proj-03",
    titleEn: "Topographic Multi-Sheet Overlay",
    titleZh: "三维等高线多层纸雕覆膜",
    categoryEn: "Architectural Visuals / Exhibition",
    categoryZh: "三维微积分建筑展览 / 实体媒介",
    year: "2026",
    roleEn: "Visual Anthropologist / Scenographer",
    roleZh: "视觉人类学者 / 展览空间设计师",
    summaryEn: "A series of physical and digital elevation maps built by layering translucent parchment and thick unbleached, raw corrugated sheets.",
    summaryZh: "一系列通过把半透明羊皮纸与厚重未漂白原始瓦楞卡纸，多层物理叠加而成的空间海拔高程交互数字等高线图谱。",
    detailsEn: "By segmenting spatial terrain coordinates into specific vector layers, we cut multiple sheets of raw unbleached card sheets. Each sheet is elevated by standard foam dividers, creating deep, physical carbon shadow offsets (Skeuomorphic shadows real-life). Users can control a mobile scanner overlay that projects active architectural blueprints onto the physical layers via high-contrast minimal grids.",
    detailsZh: "通过将地形海拔等高线划分为不同向量图层，我们切削了数层重质瓦楞卡纸并用特定泡棉垫高，在自然光下产生极其细腻逼真的实体阴影深度。观众可通过移动扫描镜片，在这些切片实体层上动态投射高对比度的CAD网格与实时像素测定数值。",
    paperGrammage: "250g Textured Parchment Over 1200g Grey Composite Card",
    colorHex: "#e8e6df",
    technicalCoordinations: ["LASER_DEPTH_LEVEL_05", "D_OFFSET: 3.5mm", "CONT_INTERVAL: 10m"],
    featuresEn: ["Layered heavy physical ambient depth", "Laser-cut coordinate alignment", "Precision hybrid projections on carbon shadow"],
    featuresZh: ["多层重质物理卡纸自然深度投影", "激光雕刻对齐针孔定位", "物理复合阴影处的精密数码投影叠层"]
  },
  {
    id: "proj-04",
    titleEn: "Kinetic Paper Folding UI",
    titleZh: "动力学折叠风琴多合一信息纸",
    categoryEn: "Interactive UI/UX & Packaging",
    categoryZh: "数字折叠交互界面 / 概念包装",
    year: "2025",
    roleEn: "Interaction Designer",
    roleZh: "交互界面设计师 & 纸张重构学者",
    summaryEn: "Translating digital layout physics of modular CSS Grid containers into standard physical accordion-fold cardboard devices.",
    summaryZh: "将数码网页中的模块化CSS网格物理映射在带有硬质卡板拼接的实体手琴页折叠设备中。",
    detailsEn: "An empirical experiment in responsive grids. We printed custom QR trackers and high-contrast digital glyphs on double-thick layout sheets with built-in folding sensors. When folded, the digital website on nearby tablets responds dynamically, reflowings lists and menus as if the physical paper folding was resizing the screen viewport. An ultra-tactile bridge.",
    detailsZh: "一场响应式网格在实体世界的重力力学实验。我们在装有精微折叠折合阻抗片的厚卡风琴褶皱页上印刷了高对比度数字逻辑符号与对齐十字。手动弯折折纸时，联动的数码设备会同步重新流式布局和变换菜单，就像是物理纸张的折合物理改变了屏幕的分辨率一般。",
    paperGrammage: "420g Heavy Ivory Pressed Bristol Board",
    colorHex: "#edeae2",
    technicalCoordinations: ["ACCORD_HINGE_R4", "VIEWPORT_RATIO: 1:1.618", "SPRING_FLEX: 2.2N/m"],
    featuresEn: ["Physical folding sensors integration", "High-thickness Ivory card weight tactile feel", "Flexible CSS Grid conceptual projection"],
    featuresZh: ["实体物理弹力阻断感应模块", "高瓦数双面涂布白卡纸超实手感", "灵活视口比例与实体弹簧系数投影"]
  }
];

export const defaultPaperElements: PaperElement[] = [
  {
    id: "pe-01",
    labelEn: "Technical Blueprint Header",
    labelZh: "底图技术框架板",
    x: 40,
    y: 30,
    width: 320,
    height: 60,
    rotate: -1,
    elevation: 3,
    color: "#fcfcfa",
    type: "header"
  },
  {
    id: "pe-02",
    labelEn: "Aesthetic Core Image Slice",
    labelZh: "核心美学意向切片",
    x: 80,
    y: 110,
    width: 240,
    height: 140,
    rotate: 2,
    elevation: 5,
    color: "#efeade",
    type: "hero-img"
  },
  {
    id: "pe-03",
    labelEn: "Geometric Grid Matrix",
    labelZh: "几何网格逻辑矩阵",
    x: 40,
    y: 270,
    width: 180,
    height: 100,
    rotate: -3,
    elevation: 2,
    color: "#faf6ed",
    type: "grid-card"
  },
  {
    id: "pe-04",
    labelEn: "Tactile Code Tag",
    labelZh: "纸质微型程序标签",
    x: 240,
    y: 270,
    width: 120,
    height: 100,
    rotate: 4,
    elevation: 4,
    color: "#e8e3d7",
    type: "circular-tag"
  }
];

export const i18n: Record<"en" | "zh", LocaleContent> = {
  en: {
    logoTitle: "TACTILE & CODE",
    subtitle: "PAPER-TEXTURIZED DIGITAL STUDIO // PORTFOLIO 2026",
    introText: "We bridge the tactile precision of luxury paper craft, unbleached cotton book sheets, and heavy debossed letterpress with cutting-edge vector geometry, responsive flexbox fluid frameworks, and generative intelligence.",
    viewDetails: "Examine Technical Spec",
    close: "Retract Sheet",
    workTitle: "SELECTED WORKS // CURATED BLUEPRINTS",
    aboutTitle: "COGNITIVE MATRIX // THE MIND BEHIND",
    labTitle: "TACTILE PLAYGROUND // GRID LAB",
    aiTitle: "AESTHETIC CRITIQUE // GEMINI NEURAL ENGRAVER",
    paperGrammageLabel: "Base Material weight",
    roleLabel: "Exhibition Role",
    gridCoordsLabel: "System Cartesian Coordinates",
    specsTitle: "PHYSICAL METRIC SPECS",
    playgroundTitle: "Visual Drafting Desk (Interactive Kraft Elements)",
    playgroundIntro: "Rearrange, scale, tilt, and stack physical layout modules. Observe real-time coordinate collision trackers, rotational offset metrics, and solid card dropshadow steps designed for draftsmen.",
    elementSelector: "Fibre Cards Inventory",
    addCard: "Stamp New Card",
    resetLayout: "Align Drafting Sheet",
    customizingElement: "ELEMENT TRANSFORM MATRIX",
    width: "Card Width (px)",
    height: "Card Height (px)",
    rotate: "Rotational Angle",
    elevation: "Pulp Depth Stack (Dropshadow Pixels)",
    coordsFeedback: "PLOTTER ARMATURE FEEDBACK COORDS // ",
    aiInputPlaceholder: "Briefly specify your craft concept (e.g., debossed canvas packaging, copper foil...).",
    critiqueHeading: "Aesthetic Critique",
    critiqueIntro: "Submit your core art draft to evaluate layout tension, print alignments, and physical feasibility.",
    getCritiqueBtn: "Run Aesthetic Critique",
    scoreCard: "AESTHETIC FITNESS",
    keywordsCard: "MATERIAL SPECIFIERS",
    analysisTab: "Analysis",
    recsTab: "Adjustments",
    tactileTab: "Materials",
    aboutIntro: "AN ARTIST UNITING MECHANICAL RIGOR WITH REFINED PAPER ORGANISM.",
    aboutBody1: "Since 2020, we have investigated mathematical, interactive digital products that behave like physical paper sheets. By referencing high-craft blind printing, linen thread binding, and paper plate textures in web applications, we restore spatial comfort and gravity to browser frames.",
    aboutBody2: "We specialize in lightweight React layouts, interactive mechanical simulations, and server-side machine learning applications that output highly structured creative directives. We believe that software design should have weight, friction, and elegant touch indicators.",
    skillsLabel: "SYSTEM CAPABILITIES",
    experienceLabel: "CHRONOLOGY SELECTS"
  },
  zh: {
    logoTitle: "纸素 & 位数",
    subtitle: "纸张触感美学 / 数字化交互作品选集 2026",
    introText: "我们跨越两个平行维度的精妙之美：高质纯棉纤维卡纸、未漂白书籍封面与压凹活字艺术，以及切割现代网页的数码像素、流式自适应弹性布局与网络生成式深度神经网络。",
    viewDetails: "查阅物理工艺细节",
    close: "收回纸页",
    workTitle: "精选艺术作品 // 工艺结构轴线",
    aboutTitle: "媒介认知论 // 作者原形",
    labTitle: "实体网格实验室 // 布局工作台",
    aiTitle: "设计审美研判",
    paperGrammageLabel: "基础承印特质",
    roleLabel: "项目承担角色",
    gridCoordsLabel: "系统笛卡尔向量坐标",
    specsTitle: "物理工艺计量规格",
    playgroundTitle: "虚拟排版草图桌 (高触感可交互纤维板块模型)",
    playgroundIntro: "拖曳、缩放、略微倾斜任意纸质排版元素。观察真实的笛卡尔空间位移碰撞追踪反馈、高阶重压纤维层积投影深浅，以及专为工程设计师配置的微米级排布游标参数。",
    elementSelector: "工程硬卡纸物料库",
    addCard: "压印一枚硬卡",
    resetLayout: "重整绘图纸张",
    customizingElement: "板块高精密参数矩阵控制",
    width: "板块横宽 (px)",
    height: "板块竖高 (px)",
    rotate: "自适应选择旋转倾角",
    elevation: "纸张叠合深度 (纸板硬投影厚度)",
    coordsFeedback: "绘图仪末端绘图臂现场反馈坐标 // ",
    aiInputPlaceholder: "请输入设计想法（如：极简铜版纸画册，压凹工艺，精细无衬线排版...）",
    critiqueHeading: "智能审美研判",
    critiqueIntro: "简单输入你的创意构想，评测材料适配性、视觉张力与落地的物理可行性。",
    getCritiqueBtn: "开始审美分析",
    scoreCard: "审美度评分",
    keywordsCard: "意向关键词",
    analysisTab: "概念评述",
    recsTab: "优化方案",
    tactileTab: "材质建议",
    aboutIntro: "一位致力于在无菌数字世界克隆物理纸张重力和摩擦阻断感的造物者。",
    aboutBody1: "自 2020 年起，我们致力于将数学逻辑与阻力物理折叠带入单调的浏览器中。在数字界面融入凸版重压、棉麻线装脊骨、微糙谷糠颗粒纸背的微影质感。通过高对比度的极简网格配以机械工业坐标轴，实现冷峻科技与温暖物性的共振。",
    aboutBody2: "我们专精于优雅而极其轻盈的 React 自定义动效架构、物理阻尼拖拽计算以及将结构化数据以极高还原度转化为物理排版的设计。我们坚信数字内容也应有厚度、有光线偏振、由于空气阻尼带来的迟滞感。",
    skillsLabel: "系统媒介能力",
    experienceLabel: "编年史典记"
  }
};
